all: projbin // output file
cc=gcc

//from where i get projbin

main.o add.o sub.o 
$(cc) -o projbin main.o add.o sub.o 

where i get main.o sub.o   add.o 


$(cc) -c -o main.o main.c

$(cc) -c -o add.o add.c

$(cc) -c -o sub.o sub.c
